version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/images/builders/java"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "docker"
    directory: "/images/builders/nodejs"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "docker"
    directory: "/images/builders/python"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "docker"
    directory: "/images/builders/golang"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "docker"
    directory: "/images/builders/toolbox"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps)"
