
###################### Below this line are code snippets split by function or module
.build_after_script:
  after_script:
    - |
      set -x
      rm -rf ~/.ssh || true
      rm -rf ~/.ash_history || true
      rm -rf ~/.bash_history || true
    - |
      # Clean up docker login lock files
      rm -rf ~/.docker-lock/${CI_PIPELINE_ID}-${CI_JOB_NAME}.lock || true
      # Only logout when all lock files are released
      if [ `ls ~/.docker-lock/*.lock|wc -l` -eq 0 ];then
          docker logout ${HARBOR_URL##https://}
          rm -rf ~/.config/glab-cli/config.yml || true
      fi

.clean_auth_files:
  after_script:
    - rm -rf ~/.npmrc || true
    - rm -rf ~/.ssh || true
    - rm -rf ~/.ash_history || true
    - rm -rf ~/.bash_history || true
    - rm -rf ~/.pip/pip.conf || true