.general_stage:
  stages:
    - sonar
    - test
    - build
    - scan
    - deploy
    - rollback

###################### Below this line are code snippets split by function or module
.runner_tag:
  tags:
    - "${RUNNER}"

.job-retry:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

.node-cache:
  cache:
    untracked: true
    key: "${CI_PROJECT_NAME}"
    paths:
      - "node_modules"

.load_artifacts_env:
  dependencies:
    - pre



# Tool shell functions, loaded in the before stage to empower the entire stage phase
.utils_shell_function:
  script:
    - |
      function shell_exec(){
          echo "${1}"|bash
      }
      # Load shell execution function to prevent alias invalidation issue, depends on bash interpreter usage
      # Usage example: shell_exec "${BUILD_SHELL}"
    - |
      # Load font color output class
      echo=echo
      for cmd in `echo /bin/echo`; do
        $cmd >/dev/null 2>&1 || continue
        if ! $cmd -e "" | grep -qE '^-e'; then
          echo=$cmd
          break
        fi
      done
    - |
      function script_download(){
        curl -fsSL --header "PRIVATE-TOKEN: ${GITLAB_READ_TOKEN}" \
          ${TEMPLATE_REPO%/devops*}/api/v4/projects/${TEMPLATE_REPO_PROJECT_ID}/repository/files/scripts%2F${1}/raw?ref=${TEMPLATE_BRANCH_NAME} -o ${2:-run.sh}
      }  # Usage: (1): script_download _utils.sh (2): script_download sonarqube.sh; Download scripts from current "scripts/" directory to stage for execution, requires a token as prerequisite
    - |
      function dockerfile_download(){
        curl -fsSL --header "PRIVATE-TOKEN: ${GITLAB_READ_TOKEN}" \
          ${TEMPLATE_REPO%/devops*}/api/v4/projects/${TEMPLATE_REPO_PROJECT_ID}/repository/files/dockerfile%2F${1}/raw?ref=${TEMPLATE_BRANCH_NAME} -o ${DOCKER_DAEMON_WORKSPACE}/${2:-Dockerfile}
      }
