.general_stage:
  stages:
    - sonar
    - test
    - build
    - scan
    - deploy
    - rollback

###################### 此分割线以下放置 拆分成段的 代码段；按功能 or 模块 进行拆分
.runner_tag:
  tags:
    - "${RUNNER}"

.job-retry:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

.node-cache:
  cache:
    untracked: true
    key: "${CI_PROJECT_NAME}"
    paths:
      - "node_modules"

.load_artifacts_env:
  dependencies:
    - pre



# 工具类 shell 函数，在 before 阶段进行载入，提供给整个 stage 阶段赋能
.utils_shell_function:
  script:
    - |
      function shell_exec(){
          echo "${1}"|bash
      }
      # 载入 shell 执行函数，防止 alias 别名失效问题，依赖 bash 解释器的使用
      # 使用示例 shell_exec "${BUILD_SHELL}"
    - |
      # 载入字体颜色输出类
      echo=echo
      for cmd in `echo /bin/echo`; do
        $cmd >/dev/null 2>&1 || continue
        if ! $cmd -e "" | grep -qE '^-e'; then
          echo=$cmd
          break
        fi
      done
    - |
      function script_download(){
        curl -fsSL --header "PRIVATE-TOKEN: ${GITLAB_READ_TOKEN}" \
          ${TEMPLATE_REPO%/devops*}/api/v4/projects/${TEMPLATE_REPO_PROJECT_ID}/repository/files/scripts%2F${1}/raw?ref=${TEMPLATE_BRANCH_NAME} -o ${2:-run.sh}
      }  # 使用方法: (1): script_download _utils.sh (2): script_download sonarqube.sh; 下载当前 "scripts/" 下的脚本至 stage 中执行, 前置条件需要一个 token
    - |
      function dockerfile_download(){
        curl -fsSL --header "PRIVATE-TOKEN: ${GITLAB_READ_TOKEN}" \
          ${TEMPLATE_REPO%/devops*}/api/v4/projects/${TEMPLATE_REPO_PROJECT_ID}/repository/files/dockerfile%2F${1}/raw?ref=${TEMPLATE_BRANCH_NAME} -o ${DOCKER_DAEMON_WORKSPACE}/${2:-Dockerfile}
      }