# .release_version: &release_version
#   if: '$CI_COMMIT_REF_NAME =~ /^(v|release)-?\d+\.\d+\.\d+(-{1}([a-zA-Z0-9]{2,8}))?(\/{1}[a-z0-9]{2,6})?$/
#     && ($CI_COMMIT_BEFORE_SHA != "0000000000000000000000000000000000000000" || $CI_PIPELINE_SOURCE == "web")'
#   variables:
#     # extends: .default_vars
#     RELEASE_BUILD: 'true' # 符合条件的，设置为 release 版本


.release_version: &release_version
  if: '$CI_COMMIT_REF_NAME =~ /^v\d+\.\d+\.\d+(-{1}([a-zA-Z0-9.]{2,8}))?$/'
  variables:
    RELEASE_BUILD: 'true'

.argocd_trigger:
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^(vk|dev|prd|sit|uat|demo|pet)((-|_)[-_0-9a-z]{1,12})?$/
    && ($CI_COMMIT_BEFORE_SHA != "0000000000000000000000000000000000000000" || $CI_PIPELINE_SOURCE == "web")'


.default_trigger_vars: &default_trigger_vars
  # extends: .default_vars
  RELEASE_BUILD: "false"


# .dev_deploy_rules: &dev_deploy_rules
#   - if: '($CI_COMMIT_REF_NAME =~ /^(dev|feat)((-|_)[-_0-9a-z]{1,12})?$/ || $DEPLOY_ENABLE == "true")
#       && $DEPLOY_REPO && DEPLOY_REPO_PROJ'
#     variables:
#       REMOTE_BRANCH: "dev"


.release_version_rules:
  rules:
     - *release_version
     - when: on_success

    
.image_scan_rules:
  rules:
    - if: '$BUILD_SHELL && $PROJECT_TYPE == "python"'
      when: never
    - if: '$CI_COMMIT_REF_NAME !~ /^(vk|feat|bugfix|hotfix)((-|_)[-_0-9a-z]{1,32})?(\/[-_0-9a-z]+)?$/ 
        && $DOCKER_IMAGE_SCAN_IMAGE == "true" && $DOCKER_IMAGE_BUILD == "true"'
    - if: '$CI_COMMIT_REF_NAME =~ /^(vk|feat|bugfix|hotfix)((-|_)[-_0-9a-z]{1,32})?(\/[-_0-9a-z]+)?$/ 
        && $DOCKER_IMAGE_BUILD == "true" && $DOCKER_IMAGE_SCAN_IMAGE == "true" && $FEAT_DOCKER_IMAGE_BUILD == "true"'

# 只有默认分支会触发 pipeline ,且需要手动确认执行。 schedule 调度任务触发时无需 手动确认
.master_schedule_manual_trigger:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" 
      && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual

# 由 触发器触发的 pipeline 不执行
.schedule_trigger_disble:
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'

###################### 此分割线以上放置 拆分成段的 代码段；按功能 or 模块 进行拆分
.develop_deploy:
  rules:
    - if: '($CI_COMMIT_REF_NAME =~ /^(vk|dev|feat)((-|_)[-_0-9a-z]{1,12})?$/ || $DEPLOY_ENABLE == "true")
        && $DEPLOY_REPO && DEPLOY_REPO_PROJ'
      variables:
        REMOTE_BRANCH: "dev"

.develop_deploy_manual:
  rules:
    - if: '($CI_COMMIT_REF_NAME =~ /^(vk|dev|feat)((-|_)[-_0-9a-z]{1,12})?$/ || $DEPLOY_ENABLE == "true")
        && $DEPLOY_REPO 
        && DEPLOY_REPO_PROJ'
      variables:
        REMOTE_BRANCH: "dev"
  when: manual

.trigger_rule:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "prd"'
      variables:
        RELEASE_BUILD: "false"
        DOCKER_IMAGE_SCAN_IMAGE: "false"
        DOCKER_IMAGE_BUILD: "false"
        SIT_CD_AUTO_DEPLOY: "false"
    - *release_version
    # 且 dev|sit|prd|feat|bugfix|hotfix 开头，已 - 进行连接 的可以触发；$CI_COMMIT_BEFORE_SHA 过滤掉创建新分支 触发
    - if: '$CI_COMMIT_REF_NAME =~ /^(vk|dev|sit)$/ 
        && ($CI_COMMIT_BEFORE_SHA != "0000000000000000000000000000000000000000" || $CI_PIPELINE_SOURCE == "web")'
      variables:
        *default_trigger_vars
    - if: '$CI_COMMIT_REF_NAME =~ /^(vk|feat|bugfix|hotfix)((-|_)[-_0-9a-z]{1,32})?(\/[-_0-9a-z]+)?$/ 
        && ($CI_COMMIT_BEFORE_SHA != "0000000000000000000000000000000000000000" || $CI_PIPELINE_SOURCE == "web")' 
      variables:
        RELEASE_BUILD: "false"
        FEAT_BRANCH: "true"
    - if: '$CI_COMMIT_REF_NAME =~ /^prd-\d+-[a-z0-9]+-[0-9]+$/'
      variables:
        extends: .default_trigger_vars

# CD 持续部署相关
.cd_deploy:
  rules:
    - if: '($BUILD_SHELL && $PROJECT_TYPE == "python") || $DEPLOY_REPO == null'
      when: never
    - if: '($CI_COMMIT_REF_NAME =~ /^prd-\d+-[a-z0-9]+-[0-9]+$/ && $PRD_BUILD_CREATE_TAG != "true") 
        ||  $CI_COMMIT_REF_NAME == "prd" || $DEPLOY_REPO == null'
      when: never
    - if: '($CI_COMMIT_REF_NAME =~ /^(vk|feat|bugfix|hotfix)((-|_)[-_0-9a-z]{1,32})?(\/[-_0-9a-z]+)?$/ || $CI_COMMIT_REF_NAME == "dev")
        &&  $FEAT_CD_AUTO_DEPLOY == "false" && $DEV_CD_AUTO_DEPLOY == "false"'
      when: manual
    - if: '($CI_COMMIT_REF_NAME =~ /^(vk|feat|bugfix|hotfix)((-|_)[-_0-9a-z]{1,32})?(\/[-_0-9a-z]+)?$/ || $CI_COMMIT_REF_NAME == "dev")
        &&  $DEV_CD_AUTO_DEPLOY == "false"'
      when: manual
    - if: '$CI_COMMIT_REF_NAME == "sit" && $SIT_CD_AUTO_DEPLOY == "false"'
      when: manual
    - if: '($CI_COMMIT_REF_NAME == "prd" || $CI_COMMIT_REF_NAME =~ /^prd-\d+-[a-z0-9]+-[0-9]+$/)
        && $SIT_CD_AUTO_DEPLOY == "false"'
      when: manual
    - if: '$CI_COMMIT_REF_NAME =~ /^(vk|feat|bugfix|hotfix)((-|_)[-_0-9a-z]{1,32})?(\/[-_0-9a-z]+)?$/ 
        && $DEPLOY_REPO && $DOCKER_IMAGE_BUILD == "true" && $FEAT_DOCKER_IMAGE_BUILD == "true" 
        && $FEAT_CD_AUTO_DEPLOY == "true"'
    - if: '$CI_COMMIT_REF_NAME !~ /^(vk|feat|bugfix|hotfix)((-|_)[-_0-9a-z]{1,32})?(\/[-_0-9a-z]+)?$/ 
        && $DEPLOY_REPO && $DOCKER_IMAGE_BUILD == "true"'
    - if: '$CI_COMMIT_REF_NAME !~ /^(vk|feat|bugfix|hotfix)((-|_)[-_0-9a-z]{1,32})?(\/[-_0-9a-z]+)?$/ 
        && $DEPLOY_REPO && $DOCKER_IMAGE_BUILD == "true"'
      when: manual
    - if: '$CI_COMMIT_REF_NAME =~ /^(vk|feat|bugfix|hotfix)((-|_)[-_0-9a-z]{1,32})?(\/[-_0-9a-z]+)?$/ 
        && $DEPLOY_REPO && $DOCKER_IMAGE_BUILD == "true" && $FEAT_DOCKER_IMAGE_BUILD == "true"'
      when: manual