include:
  - local: "vars/*.latest.gitlab-ci.yml"
  - local: "utils/*.latest.gitlab-ci.yml"
  - local: "jobs-templates/PreJob.latest.gitlab-ci.yml"
  - local: "jobs-templates/SonarQube.latest.gitlab-ci.yml" # SonarQube code scan
  - local: "jobs-templates/Test.latest.gitlab-ci.yml" # Unit test
  - local: "jobs-templates/Build.latest.gitlab-ci.yml"
  - local: "jobs-templates/Trivy-Container-Scanning.latest.gitlab-ci.yml"
  - local: "jobs-templates/Gitlab-Container-Scanning.latest.gitlab-ci.yml"
  - local: "jobs-templates/Deploy.latest.gitlab-ci.yml"
  - local: "jobs-templates/Rollback.latest.gitlab-ci.yml"
  # Multi-architecture build support (optional, enabled via variable)
  - local: "vars/multiarch-vars.latest.gitlab-ci.yml"

# Load default variables, variable values can be overridden by upper levels
# Variable priority: script(bash) > gitlab web > gitlab template > os system default;
# Among them, gitlab web also has priority issues:
# gitlab project > gitlab group > gitlab platform default
variables:
  extends: .default_vars
  TEMPLATE_CONTEXT: 'latest'

cache:
  paths:
    - ${CACHE_DIR}

stages:
  !reference [ .general_stage, stages ]

workflow:
  rules:
    !reference [ .trigger_rule, rules ]
