include:
  - local: "vars/*.latest.gitlab-ci.yml"
  - local: "utils/*.latest.gitlab-ci.yml"
  - local: "jobs-templates/PreJob.latest.gitlab-ci.yml"
  - local: "jobs-templates/SonarQube.latest.gitlab-ci.yml" # sonaruqbe 代码扫描
  - local: "jobs-templates/Test.latest.gitlab-ci.yml" # 单元测试
  - local: "jobs-templates/Build.latest.gitlab-ci.yml"
  - local: "jobs-templates/Trivy-Container-Scanning.latest.gitlab-ci.yml"
  - local: "jobs-templates/Gitlab-Container-Scanning.latest.gitlab-ci.yml"
  - local: "jobs-templates/Deploy.latest.gitlab-ci.yml"
  - local: "jobs-templates/Rollback.latest.gitlab-ci.yml"
  # 多架构构建支持（可选，通过变量启用）
  - local: "vars/multiarch-vars.latest.gitlab-ci.yml"

# 载入默认变量 ，变量值可以被上层替换，详情查看链接: https://gitlab.cpinnov.run/devops/ci-templates/-/blob/devops/vars/default-vars.stable.gitlab-ci.yml
# 变量优先级  script(bash) > gitlab web >  gitlab template > os system default;
# 其中 gitlab web 又存在有优先级问题：
# gitlab project > gitlab group > gitlab platform default
variables:
  extends: .default_vars
  TEMPLATE_CONTEXT: 'latest'

cache:
  paths:
    - ${CACHE_DIR}

stages:
  !reference [ .general_stage, stages ]

workflow:
  rules:
    !reference [ .trigger_rule, rules ]