include:
  - local: "vars/*.stable.gitlab-ci.yml"
  - local: "utils/*.stable.gitlab-ci.yml"
  - local: "jobs-templates/SonarQube.gitlab-ci.yml" # sonarqube 代码扫描

variables:
  extends: .default_vars

default:
  image: ${GO_IMAGE}

cache:
  paths:
    - ${CACHE_DIR}

stages:
  !reference [ .general_stage, stages ]

test:
  extends:
    - .go_test
    - .unit_test_base

build:
  extends:
    - .go_build
    - .build_base

scan:
  extends:
    - .image_scan_base

deploy:
  extends:
    - .iamge_deploy_base

workflow:
  rules:
    !reference [ .trigger_rule, rules ]

