include:
  - local: "vars/*.stable.gitlab-ci.yml"
  - local: "utils/*.stable.gitlab-ci.yml"

# Reference all split steps, provide flexible reuse for projects.

default:
  image: ${TOOLBOX_IMAGE}

variables:
  extends: .default_vars