include:
  - local: "vars/*.stable.gitlab-ci.yml"
  - local: "utils/*.stable.gitlab-ci.yml"

# 引用所有的 拆分步骤，提供给 project 进行 灵活复用。

default:
  image: ${TOOLBOX_IMAGE}
  
variables:
  extends: .default_vars