include:
  - local: "vars/*.latest.gitlab-ci.yml"
  - local: "utils/*.latest.gitlab-ci.yml"
  - local: "jobs-templates/SonarQube.gitlab-ci.yml"

variables:
  extends: .default_vars

default:
  image: ${NODE_IMAGE}

cache:
  paths:
    - ${CACHE_DIR}

stages:
  !reference [ .general_stage, stages ]

test:
  extends:
    - .npm_test
    - .unit_test_base

build:
  extends:
    - .npm_build
    - .build_base

scan:
  extends:
    - .image_scan_base

deploy:
  extends:
    - .image_deploy_base

workflow:
  rules:
    !reference [ .trigger_rule, rules ]
