# Global public variables
include:
  - remote: 'https://raw.githubusercontent.com/cdryzun/gitlab-ci-templates/open/jobs-templates/argocd.latest.gitlab-ci.yml'

variables:
  GLOBAL_DOMAIN: "example.com"
  # Deployment project repository address
  REPO_URL: "${CI_PROJECT_URL}.git"
  # Project name defined by deployment tool, need to get from operations
  ARGOCD_PROJECT: "${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}"
  # Environment domain
  ENV_URL: "http://${CI_COMMIT_BRANCH}.${CI_PROJECT_NAMESPACE}.${GLOBAL_DOMAIN}"
  # Production domain
  PROD_DOMAIN: "${CI_PROJECT_NAME}.${CI_PROJECT_NAMESPACE}.${GLOBAL_DOMAIN}"
  KUBE_NAMESPACE: "${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}"
  ARGOCD_ENV: "${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}"
