include:
  - remote: 'https://raw.githubusercontent.com/cdryzun/gitlab-ci-templates/open/jobs-templates/Auto-DevOps.latest.gitlab-ci.yml'


### Feature switches please refer to vars/default-vars.latest.gitlab-ci.yml file in the project


###############################  JAVA Project Example
# variables:
#   BUILD_SHELL: "mvn clean package -Dmaven.test.skip=true"
#   UNIT_TEST_ENABLE: "true"

### JAVA Project Example, jar package generated not in the first level directory
# variables:
#   BUILD_SHELL: "mvn clean install -Dmaven.test.skip=true \
#     && mkdir -p ./target \
#     && mv spring-cloud-gateway/target/spring-cloud-gateway.jar ./target/app.jar"
#   UNIT_TEST_ENABLE: "true"

### JAVA Scaffold Project, do not build image, only upload artifacts to repository
# variables:
#   BUILD_SHELL: "mvn clean install -Dmaven.test.skip=true \
#     && mkdir -p ./target \
#     && mv spring-cloud-gateway/target/spring-cloud-gateway.jar ./target/app.jar"
#   UNIT_TEST_ENABLE: "true"
#   DOCKER_IMAGE_BUILD: "false" # Do not build image

### For default pom.xml project build file not in the top level
# variables:
#   BUILD_MAVEN_POM_FILE: "spring-cloud-gateway/pom.xml"
#   BUILD_SHELL: "mvn clean install -Dmaven.test.skip=true \
#     && mkdir -p ./target \
#     && mv spring-cloud-gateway/target/*.jar ./target/app.jar"
#   UNIT_TEST_ENABLE: "true"


#-----------------------------------------------------

###############################   WEB Project Example
# variables:
#   BUILD_SHELL: "pnpm run dist"
#   UNIT_TEST_ENABLE: "false"

### WEB Project Example, package according to different environments, environment variable takes ${BUILD_ENV}
# variables:
#   BUILD_SHELL: "pnpm run ${BUILD_ENV}"
#   UNIT_TEST_ENABLE: "false"

### WEB Project Example, output result is not default dist, use mv to rename
# variables:
#   BUILD_SHELL: "pnpm run dist && mv docs dist"
#   UNIT_TEST_ENABLE: "false"
