include:
  - project: 'kunlun/devops/gitlabci-templates'
    ref: master
    file: 'Jobs/default.yml'
  - project: 'kunlun/devops/gitlabci-templates'
    ref: master
    file: 'Jobs/test.yml'
  - project: 'kunlun/devops/gitlabci-templates'
    ref: master
    file: 'Jobs/scan.yml'
  - project: 'kunlun/devops/gitlabci-templates'
    ref: master
    file: 'Jobs/build.yml'
  - project: 'kunlun/devops/gitlabci-templates'
    ref: master
    file: 'Jobs/deploy.yml'
  - project: 'kunlun/devops/gitlabci-templates'
    ref: master
    file: 'Jobs/sonar.yml'


workflow:
  rules:
    - if: "$CI_MERGE_REQUEST_ID"          
      when: never
    - if: "$CI_COMMIT_BEFORE_SHA == '0000000000000000000000000000000000000000'" 
      when: never
    # 默认策略为运行
    - when: always

stages:
  - sonar
  - test
  - build
  - scan
  - deploy
