# Import public templates
include:
  - remote: 'https://raw.githubusercontent.com/cdryzun/gitlab-ci-templates/open/jobs-templates/custom.latest.gitlab-ci.yml'

# Load default variables, variable values can be overridden by upper levels
# Variable priority: script(bash) > gitlab web > gitlab template > os system default;
# Among them, gitlab web also has priority issues:
# gitlab project > gitlab group > gitlab platform default
variables:
  extends: .default_vars

# sonar:
#   extends:
#     - .custom_scan_base
#   script:
#     - !reference [ .maven-generate-config, script ]
#     - |
#       cat > run.sh << EOF
#       set -eo # Enable pipeline mode, if an error occurs during execution, subsequent steps will not be executed, not recommended to delete.
#       # ====================》 Write your custom scripts after this section
#       EOF
#       chmod a+x ./run.sh \
#       && shell_exec ./run.sh

test:
  extends:
    - .maven_test
    - .unit_test_base
    - .runner_tag

build:
  extends:
    - .custom_build
  script:
    - |
      cat > run.sh << EOF
      set -eo # Enable pipeline mode, if an error occurs during execution, subsequent steps will not be executed.
      pnpm install
      pnpm run build
      EOF
      chmod a+x ./run.sh \
      && shell_exec ./run.sh

# build1:  Name should not duplicate with build above
#   image: ${NODE_IMAGE}  # Replace image according to project, default uses ${MAVEN_IMAGE}, see default_image_vars for list details
#   extends:
#     - .custom_build
#   script:
#     - |
#       export IMG_NAME="${DOCKER_REGISTRY}/${CI_PROJECT_NAMESPACE}/portal-ui"  # Replace default docker image name
#     - |
#       cat > run.sh << EOF
#       set -eo # Enable pipeline mode, if an error occurs during execution, subsequent steps will not be executed, not recommended to delete.
#       # ====================》 Write your custom scripts after this section
#       EOF
#       chmod a+x ./run.sh \
#       && shell_exec ./run.sh

deploy:
  stage: deploy
  extends:
    - .runner_tag
  script:
    - echo 'hello'
