variables:
  # -------------Advanced Configuration (Generally no configuration needed, use defaults. Configure carefully if needed)----------------------

  # Image vulnerability scanning
  DOCKER_IMAGE_SCAN_IMAGE: "true"

  # If vulnerability level is medium-high or above, force CI interruption
  ENFORCE_EXIT: "false"

  # Default preset SonarQube scan directory
  SONAR_DIR: "./src"

  # docker image artifact repository, no modification needed by default
  HARBOR_URL: "https://harbor.iquantex.com"

  # Additional parameters added during docker build, such as "--no-cache" to build without cache, multiple parameters separated by space
  DOCKER_BUILD_FLAGS: ''


include:
  - remote: 'https://raw.githubusercontent.com/cdryzun/gitlab-ci-templates/open/jobs-templates/default.stable.gitlab-ci.yml'


# Custom project build job, job name is fixed as build, please do not change.
# build:
#   #--Inherit common template variables and parameters---start--
#   image: "${MAVEN_IMAGE}"
#   extends:
#     - .before_jobs
#     - .nexus_auth
#     - .harbor_auth
#     - .runner_tag
#     - .build_after_script
#   #--Inherit common template variables and parameters---end--
#   script:
#     # Inherit template actions, generate default configuration, uncomment as needed.
#     - !reference [ .maven-generate-config, script ]
#     - !reference [ .npm-generate-config, script ]
#     - !reference [ .docker_login, script ]
#     # Custom command 1
#     - echo "command1"
#     # Custom command 2
#     - echo "command2"
#     # Custom command
#     - echo "command3"
