variables:
  # -------------Basic Configuration----------------------
  # Command executed during Gradle build, change according to your needs. Use "&&" to connect multiple commands
  BUILD_SHELL: "gradle clean build -x test"

  # Whether to execute unit tests
  GRADLE_TEST: "false"

  # Gradle test command
  TEST_SHELL: ""

  # Default sonarqube scan directory
  SONAR_DIR: "./src"

  # Whether to build docker image after package build completes
  DOCKER_IMAGE_BUILD: "true"

  # -------------Advanced Configuration (Generally no need to configure, use defaults, if needed please read comments carefully)----------------------

  # Image vulnerability scanning
  DOCKER_IMAGE_SCAN_IMAGE: "false"

  # Force interrupt CI if vulnerability level is medium-high or above
  ENFORCE_EXIT: "false"

  # Sonarqube scan binary directory, multiple separated by ","
  # Gradle default output directory is different from Maven
  SONAR_BINARIES: 'build/classes'

  # Sonarqube scan test binary directory, multiple separated by ","
  SONAR_TEST_BINARIES: 'build/test-classes'

  # Sonarqube address to use, configure SONAR_URL in GitLab CI/CD variables
  # SONAR_URL: "https://sonarqube.example.com"

  # Gradle generated jar package name, default app
  # MAVEN_APP_NAME: "app"

  # Cache directory for staged builds
  # Gradle cache directory includes build directory and .gradle directory
  CACHE_DIR: "build/"

  # "Prefix" of docker image generated for DEV environment, below will generate dev-xxx tag image by default.
  # DEV_DOCKER_TAG_PERFIX: 'dev'

  # Docker image artifact repository, no need to modify by default
  # DOCKER_REGISTRY: "docker.io"

  # Additional parameters added during docker build, such as "--no-cache" to not add cache during build, multiple parameters separated by space
  DOCKER_BUILD_FLAGS: ''

  # Gradle project uses generic sonar scan
  SONAR_MAVEN: "false"

  # Non-java generic sonar scan, use sonar-scanner-cli command line for integrated scan
  SONAR_COMMON: "true"

include:
  - remote: 'https://raw.githubusercontent.com/cdryzun/gitlab-ci-templates/open/jobs-templates/gradle.stable.gitlab-ci.yml'


  # Custom backend project build task command
# build:
#   image: "${GRADLE_IMAGE:-${MAVEN_IMAGE}}"
#   extends:
#     - .before_jobs
#     - .harbor_auth
#     - .runner_tag
#     - .build_after_script
#   script:
#     - !reference [ .docker_login, script ]
#     # Custom command 1
#     - shell_exec "gradle clean"
#     # Custom command 2
#     - shell_exec "gradle build"
