variables:
  # -------------Basic Configuration----------------------
  # Command executed during maven build, change according to your needs. Use "&&" to connect multiple commands
  BUILD_SHELL: "mvn clean package -Dmaven.test.skip=true"

  # Whether to execute unit tests
  MAVEN_TEST: "false"

  # Java test command
  TEST_SHELL: ""

  # Default sonarqube scan directory
  SONAR_DIR: "./src"

  # Whether to build docker image after package build completes
  DOCKER_IMAGE_BUILD: "true"

  # -------------Advanced Configuration (Generally no need to configure, use defaults, if needed please read comments carefully)----------------------

  # Image vulnerability scanning
  DOCKER_IMAGE_SCAN_IMAGE: "false"

  # Force interrupt CI if vulnerability level is medium-high or above
  ENFORCE_EXIT: "false"

  # Sonarqube scan binary directory, multiple separated by ","
  SONAR_BINARIES: 'target/classes'

  # Sonarqube scan test binary directory, multiple separated by ","
  SONAR_TEST_BINARIES: 'target/test-classes'

  # Sonarqube address to use, configure SONAR_URL in GitLab CI/CD variables
  # SONAR_URL: "https://sonarqube.example.com"

  # Maven generated jar package name, default app
  # MAVEN_APP_NAME: "app"

  # Cache directory for staged builds
  CACHE_DIR: "target/"

  # "Prefix" of docker image generated for DEV environment, below will generate dev-xxx tag image by default.
  # DEV_DOCKER_TAG_PERFIX: 'dev'

  # Docker image for java service build, no need to modify by default. If /Dockerfile or /docker/Dockerfile exists in current repository, this will be omitted and replaced.
  # JAVA_DEFAULT_DOCKERFILE: "${TEMPLATE_REPO}/-/raw/main/dockerfile/Dockerfile-java.stable"

  # Docker image artifact repository, no need to modify by default
  # DOCKER_REGISTRY: "docker.io"

  # Maven build tool, repository address to use, default uses Maven Central
  # MAVEN_REGISTRY: "https://repo1.maven.org/maven2/"

  # Additional parameters added during docker build, such as "--no-cache" to not add cache during build, multiple parameters separated by space
  DOCKER_BUILD_FLAGS: ''



  # Java project uses maven integrated sonar scan, choose one with SONAR_COMMON below
  SONAR_MAVEN: "true"

  # Non-java generic sonar scan, use sonar-scanner-cli command line for integrated scan
  SONAR_COMMON: "false"

include:
  - remote: 'https://raw.githubusercontent.com/cdryzun/gitlab-ci-templates/open/jobs-templates/java.stable.gitlab-ci.yml'


  # Custom backend project build task command
# build:
#   #--Inherit variables and parameters from public template---start--
#   image: "${MAVEN_IMAGE}"
#   extends:
#     - .before_jobs
#     - .nexus_auth
#     - .harbor_auth
#     - .runner_tag
#     - .build_after_script
#   #--Inherit variables and parameters from public template---end--
#   script:
#     # Inherit template actions, generate default configuration, do not modify this line.
#     - !reference [ .maven-generate-config, script ]
#     - !reference [ .docker_login, script ]
#       # Because mvn uses alias to specify specific setting.xml when executing, need to wrap with shell_exec function to execute, example below:
#     # Custom command 1
#     - shell_exec "mvn build"
#     # Custom command 2
#     - shell_exec "mvn package"
#     # Custom command
#     - shell_exec "mvn clean"
