variables:
  # -------------Basic Configuration----------------------
  # Whether to enable unit tests
  PY_TEST: "true"

  # Command executed when building wheel package, modify as needed. When multiple commands exist, use "&&" to connect. For complex operations, write a build.sh in the project root directory.
  BUILD_SHELL: ""

  # Whether to build docker image after package build is complete. If no package build is needed, just enable image build.
  DOCKER_IMAGE_BUILD: "true"

  # -------------Advanced Configuration (Generally no configuration needed, use defaults. Configure carefully if needed)----------------------

  # Image vulnerability scanning
  DOCKER_IMAGE_SCAN_IMAGE: "true"

  # If vulnerability level is medium-high or above, force CI interruption
  ENFORCE_EXIT: "false"

  # Default preset SonarQube scan directory
  SONAR_DIR: "./src"

  # docker image artifact repository, no modification needed by default
  HARBOR_URL: "harbor.example.com"

  # Additional parameters added during docker build, such as "--no-cache" to build without cache, multiple parameters separated by space
  DOCKER_BUILD_FLAGS: ''


include:
  - project: 'devops/ci-templates'
    ref: devops
    file: 'jobs-templates/python.stable.gitlab-ci.yml'


# Custom project build job, job name is fixed as build, please do not change.
# build:
#   #--Inherit common template variables and parameters---start--
#   image: "${MAVEN_IMAGE}"
#   extends:
#     - .before_jobs
#     - .nexus_auth
#     - .harbor_auth
#     - .runner_tag
#     - .build_after_script
#   #--Inherit common template variables and parameters---end--
#   script:
#     # Inherit template actions, generate default configuration, uncomment as needed.
#     - !reference [ .maven-generate-config, script ]
#     - !reference [ .npm-generate-config, script ]
#     - !reference [ .docker_login, script ]
#     # Custom command 1
#     - echo "command1"
#     # Custom command 2
#     - echo "command2"
#     # Custom command
#     - echo "command3"
