variables:
  # -------------Basic Configuration----------------------
  # Command executed during frontend build. When multiple commands exist, use "&&" to connect. Use "PACKAGE_MANAGER" for yarn builds
  BUILD_SHELL: "pnpm run build"

  # Default preset SonarQube scan directory
  SONAR_DIR: "./app"

  # Whether to execute unit tests
  NPM_TEST: "false"

  # Command executed when unit tests are enabled. When multiple commands exist, use "&&" to connect
  TEST_SHELL: "pnpm install && pnpm run test"

  # Specify custom nginx config to use, default is docker/nginx.conf in project
  CUSTOM_NGINX_CONF: "docker/nginx.conf"

  # -------------Advanced Configuration (Generally no configuration needed, use defaults. Configure carefully if needed)----------------------

  # Whether to delete pnpm lock file. If version locking is required during build, do not enable this parameter, force use versions specified in lock file
  PNPM_LOCKFILE_DISABLE: "false"

  # Node.js V8 engine memory heap configuration. Some applications need this parameter during build. Not required unless needed.
  # NODE_OPTIONS: "--max-old-space-size=4096"

  # Image vulnerability scanning
  DOCKER_IMAGE_SCAN_IMAGE: "true"

  # If vulnerability level is medium-high or above, force CI interruption
  ENFORCE_EXIT: "false"

  # Frontend packaging generated static folder. Default is dist, no need to change
  STATIC_FILE_NAME: "dist"

  # Whether to build docker image after package build is complete
  DOCKER_IMAGE_BUILD: "true"

  # Whether to disable dependency installation cache. When set to true, dependencies are re-fetched from private repository each time. Increases build time. Not recommended to enable.
  NODE_CACHE_DISABLE: "false"

  # Frontend package manager selection (pnpm/yarn)
  PACKAGE_MANAGER: "pnpm"

  # Staging build cache directory
  CACHE_DIR: "dist/"

  # Additional parameters added during docker build, such as "--no-cache" to build without cache, multiple parameters separated by space
  DOCKER_BUILD_FLAGS: ''


include:
  - remote: 'https://raw.githubusercontent.com/cdryzun/gitlab-ci-templates/open/jobs-templates/web.stable.gitlab-ci.yml'


# Custom frontend build job command
# build:
#   #--Inherit common template variables and parameters---start--
#   image: "${NODE_IMAGE}"
#   extends:
#     - .before_jobs
#     - .build_after_script
#     - .nexus_auth
#     - .harbor_auth
#     - .runner_tag
#   #--Inherit common template variables and parameters---end--
#   script:
#     # Inherit template actions, generate default configuration. Do not modify this line.
#     - !reference [ .npm-generate-config, script ]
#     - !reference [ .docker_login, script ]
#     # Custom command 1
#     - pnpm install
#     # Custom command 2
#     - pnpm run build dist
#     # Custom command n
#     - pnpm run build prod
